on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            ### Hello @${{ github.actor }}, thank you for raising the issue. </br></br>

            Currently, the issue is marked as https://github.com/tamalCodes/Milan/labels/%F0%9F%91%B7%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20status%3A%20awaiting%20triage which means that work for this issue is on hold and we are waiting for the maintainers/owner to review it and provide you with feedback/suggestions to proceed further.


            Feel free to reach out to [Tamal](https://twitter.com/tamalCodes) on **Twitter**, or drop a mail at tamalcodes@gmail.com if you think that this issue is of critical priority. </br></br>

            **Give us a ⭐ to show some support**
            **Happy OpenSource 🚀**<p></p>

          pr-message: |
            ### Hello @${{ github.actor }}, thank you for raising a pull request. </br></br>

            Currently, the pull request is marked as https://github.com/tamalCodes/Milan/labels/%F0%9F%91%B7%F0%9F%8F%BB%E2%80%8D%E2%99%82%EF%B8%8F%20status%3A%20awaiting%20triage which means that work for this issue is on hold and we are waiting for the maintainers/owner to review it and provide you with feedback/suggestions to proceed further.


            Feel free to reach out to [Tamal](https://twitter.com/tamalCodes) on **Twitter**, or drop a mail at tamalcodes@gmail.com if you think that this pull request is of critical priority. </br></br>

            **Give us a ⭐ to show some support**
            **Happy OpenSource 🚀**<p></p>
